namespace BsEnums
{	

  public enum EN_AGGREGATE_TYPE
  {
	enEN_AGGREGATE_TYPE_UNKNOWN = -1,
	enEN_AGGREGATE_TYPE_STANDARD,
	enEN_AGGREGATE_TYPE_BLOWER,
	enEN_AGGREGATE_TYPE_SCRAPER,
	enEN_AGGREGATE_TYPE_TRIMMER,
	enEN_AGGREGATE_TYPE_COLLECTOR,
	enEN_AGGREGATE_TYPE_TRIM_SCR,
	enEN_AGGREGATE_TYPE_SCR_TRIM,
	enEN_AGGREGATE_TYPE_STD_TILT,
	enEN_AGGREGATE_TYPE_INTCOLLECTOR
  }

}