using System;

namespace BsEnums
{
    
  public enum EN_CLSS_RETURN_CODE
  {
	CCE_INTERNAL_POINT = 1,
	CCE_EXTERNAL_POINT = 2,
	CCE_EXTREME_POINT = 3,
	CCE_FIRST_EXTREME = 4,
	CCE_SECOND_EXTREME = 5,
	CCE_LEFT_POINT = 6,
	CCE_RIGHT_POINT = 7,
	CCE_POINT_ON_LINE = 8,
	CCE_POINT1_INTERNAL = 9,
	CCE_POINT2_INTERNAL = 10,
	CCE_TWO_INTERNAL_POINTS = 11,
	CCE_OK = 0,
	CCE_NOT_OK = -1,
	CCE_ARCTO_COICIDENT = -2,
	CCE_ARCTO_RADIUS = -3,
	CCE_POINT_OUT_LINE = -4,
	CCE_POINT_OUT_CIRCLE = -5,
	CCE_COINCIDENT_LINES = -6,
	CCE_PARALLEL_LINES = -7,
	CCE_IMAGINARY_SOLUTION = -8,
	CCE_INFINITY_SOLUTION = -9,
	CCE_CONCENTRIC_CIRCLES = -10,
	CCE_EXTERNAL_CIRCLES = -11,
	CCE_INTERNAL_CIRCLES = -12,
	CCE_COINCIDENT_CIRCLES = -13,
	CCE_NO_INTERNAL_POINT = -14,
	CCE_LINE_OUT_CIRCLE = -15,
	CCE_RADIUS_TOO_BIG = -16,
	CCE_RADIUS_TOO_SMALL = -17
  }

}